config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}
  devise_scope :user do
    get 'users/list' => 'users#index'
    get 'users/report' => 'users#report'
    get 'users/:id' => 'users#show'
    delete '/users/logout' => 'devise/sessions#destroy'
  end
  get 'users/edit'
  post 'users/edit_save'
  resources :users
  
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  root 'home#page'
  get 'home/page'
  get 'home/support_contact'
  get 'home/about'

  get 'seed/start'
  post 'seed/start'
  get 'seed/load_file'
  post 'seed/save_file'
  get 'seed/discovery'
  post 'seed/discovery'
  get 'seed/distest'
  post 'seed/distest'
  get 'seed/confirm_email'
  post 'seed/confirm_email'

  get 'domains/index'
  get 'domains/show'
  get 'domains/edit'
  post 'domains/edit_domain'
  post 'domains/save_domain'
  post 'domains/edit'
  post 'domains/update'
  delete 'domains/destroy'
  get 'domains/load_file'
  post 'domains/save_file'
  get 'domains/import'
  get 'domains/search'
  get 'domains/search_list'
  post 'domains/search_list'
  post 'domains/save_import'

  get 'cidrs/index'
  get 'cidrs/edit'
  get 'cidrs/import'
  post 'cidrs/save_import'
  post 'cidrs/edit'
  get 'cidrs/load_file'
  post 'cidrs/save_file'

  get 'hosts/index'
  post 'hosts/edit'
  get 'hosts/load_file'
  post 'hosts/save_file'

  get 'support/faq'
  get 'support/contact'

  get 'sites/index'
  get 'sites/show'
  post 'sites/edit'
  get 'sites/load_file'
  post 'sites/save_file'
  post 'sites/search'
  post 'sites/download'

  get 'logs/list'
  get 'logs/show'
  post 'logs/download'

  get 'yml_settings/index'
  get 'yml_settings/load_file'
  post 'yml_settings/save_file'

  get 'reports/index'
  get 'reports/new'
  get 'reports/download'
  get 'reports/download_all'
  resources :reports

  resources :uploads, only: [:new, :create, :destroy]
  get '/uploads/dt'
  get '/uploads/division_1'
  get '/uploads/division_2'
  get '/uploads/division_3'
  post "uploads/update"
  get "uploads/refresh"
  get "uploads/create"
  get "uploads/alert_uploads"

  get 'domain_map/show'
  post 'domain_map/show'

  get 'site_urls/display'
  post 'site_urls/download'
  resources :site_urls

end

app/models/site_url.rb
class SiteUrl < ApplicationRecord
end

app/controllers/site_urls_controller.rb
#--
# www_wmap
#
# A  Ruby application for enterprise web application asset tracking
#
# Developed by Sam (Yang) Li, <yang.li@owasp.org>.
#
#++

class SiteUrlsController < ApplicationController
  before_action :set_site_url, only: %i[ show edit update destroy display]
  before_action :authenticate_user!
  include SiteUrlsHelper

  # GET /site_urls or /site_urls.json
  def index
    @site_urls = SiteUrl.all.order(sort_column + " " + sort_direction).page(params[:page]).per_page(25)
  end

  # Render the site urls in the tree structure
  def display
    urls = SiteUrl.where(:site => params[:site]).map(&:url) - [nil,""]
    #render plain: urls
    @tree = urls.count>0? urls_2_tree(params[:site],urls) : []
    @site = params[:site]
    #@tree=[{"id"=>"https://www.google.com/", "text"=>"https://www.google.com/", "children"=>[{"id"=>"images", "text"=>"images", "children"=>[{"id"=>"icon.png", "text"=>"icon.png", "children"=>[], "icon"=>"glyphicon glyphicon-list", "state"=>{"opened"=>true}}], "icon"=>"glyphicon glyphicon-list", "state"=>{"opened"=>true}}], "icon"=>"glyphicon glyphicon-list", "state"=>{"opened"=>true}}]
    logger.debug("tree: #{@tree}")
    respond_to do |format|
      format.html
      format.json { render json: @tree }
    end
  end

  # GET /site_urls/1 or /site_urls/1.json
  def show
  end

  # GET /site_urls/new
  def new
    @site_url = SiteUrl.new
  end

  # GET /site_urls/1/edit
  def edit
  end

  # POST /site_urls or /site_urls.json
  def create
    @site_url = SiteUrl.new(site_url_params)

    respond_to do |format|
      if @site_url.save
        format.html { redirect_to @site_url, notice: "Site url was successfully created." }
        format.json { render :show, status: :created, location: @site_url }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @site_url.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /site_urls/1 or /site_urls/1.json
  def update
    respond_to do |format|
      if @site_url.update(site_url_params)
        format.html { redirect_to @site_url, notice: "Site url was successfully updated." }
        format.json { render :show, status: :ok, location: @site_url }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @site_url.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /site_urls/1 or /site_urls/1.json
  def destroy
    @site_url.destroy
    respond_to do |format|
      format.html { redirect_to site_urls_url, notice: "Site url was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  # allow user to download url table into Excel file
  def download
    if platinum_user_and_above?
      urls=SiteUrl.where("site is not null")
      workbook = RubyXL::Workbook.new
      worksheet = workbook.worksheets[0]
      worksheet.sheet_name = 'urls'
      header = ["Site","Url","Last Update"]
      index = 0
      worksheet_write_row(worksheet,index,header)
      urls.each do |url|
        next if url.site.nil?
        next if url.site.empty?
        index += 1
        my_row = [url.site, url.url, url.updated_at]
        worksheet_write_row(worksheet,index, my_row)
      end
      file = "Discovered_Urls_" + Time.now.strftime('%m%d%Y') + ".xlsx"
      send_data workbook.stream.string, filename: file, disposition: 'attachment'
    else
      redirect_back :fallback_location => root_path, :alert => "Access denied."
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_site_url
      @site_url = SiteUrl.find(params[:id]) if params[:id]
    end

    # Only allow a list of trusted parameters through.
    def site_url_params
      params.require(:site_url).permit(:site, :url, :req_method, :code)
    end

    def sort_column
      SiteUrl.column_names.include?(params[:sort]) ? params[:sort] : "site"
    end

    def sort_direction
      %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
    end

end

app/helpers/site_urls_helper.rb
#--
# www_wmap
#
# A  Ruby application for enterprise web application asset tracking
#
# Developed by Sam (Yang) Li, <yang.li@owasp.org>.
#
#++

module SiteUrlsHelper

  # Reload site table based on the current WMAP discovery data file
  def site_urls_table_update(uid,data_dir)
    puts "Update the site url table ..."
    db = Sequel.connect(ENV['DATABASE_URL'])
    puts "Database connection success. "
    urls_table = db[:site_urls]
    #site_table.truncate
    #puts "site table truncate success."
    tracker=Wmap::SiteTracker.instance
    tracker.data_dir=data_dir
    tracker.sites_file = tracker.data_dir + "/" + "sites"
    tracker.load_site_stores_from_file(tracker.sites_file)
    urls_file = tracker.data_dir + "/logs/" + "cur_urls.log"
    urls = tracker.file_2_list(urls_file)
    sites = tracker.known_sites.keys
    urls.map do |url|
      next if url.nil? || url.empty?
      site = tracker.url_2_site(url).downcase
      if sites.include?(site)
        url_count = urls_table.where(:url =>url).count
        if url_count < 1
          puts "Insert record for url: #{url}"
          urls_table.insert(site: site,  url: url, user_id: uid, created_at: Time.now, updated_at: Time.now)
        else
          puts "Update the url timestamps: #{url}"
          urls_table.where(:url =>url).update(updated_at: Time.now)
        end
      else
        next
      end
    end
    tracker=nil
    db = nil
    puts "Update complete. "
  end

  # parse the urls list then generate the tree data structure
  def urls_2_tree (site, urls)
    $tree = []
    $tree << { 'text' => site,
               'children' => [], 'icon' => 'glyphicon glyphicon-list',
               'state' => { 'opened' => true } }
    urls.map do |url|
      u = url.split(site)
      if u[1].nil?
        next
      else
        nodes = u[1].split('/') - [nil,""]
        traverse_tree_branch($tree[0], nodes)
      end
    end
    return $tree
  end

  # traverse the tree branches and build the data structure in json
  def traverse_tree_branch(branch,nodes)
    node = nodes.shift
    cnt = branch['children'].count
    puts "node: #{node}"
    if has_node(branch,node)
      i = get_branch_index(branch,node)
      if nodes.count <= 0    # end of leaf
        return
      else
        traverse_tree_branch(branch['children'][i], nodes)
      end
    else
      branch['children'] << {
                  'text' => node,
                  'children' => [], 'icon' => 'glyphicon glyphicon-list',
                  'state' => { 'opened' => true }
      }
      if nodes.count <= 0    # end of leaf
        return
      else
        traverse_tree_branch(branch['children'][cnt],nodes)
      end
    end
  end

  # check if the node was existing in the tree branch
  def has_node(branch,node)
    default = false
    return false if branch['children'].count==0
    branch['children'].map do |leaf|
      if leaf['text'] == node
        return true
      end
    end
    return default
  end

  # Given branch is certain of the existing tree, found the index of the branch in the tree
  def get_branch_index(branch,node)
    branch['children'].each_with_index.map do |l,i|
      return i if l['text'] == node
    end
  end

  # write an worksheet row
  def worksheet_write_row(worksheet, index, my_row)
    puts "Writing record into the spreadsheet: #{my_row}"
    (0...my_row.count).map do |col|
      worksheet.add_cell(index, 0, '') if worksheet[index].nil?
      worksheet.add_cell(index,col,'') if worksheet[index][col].nil?
      puts "Write to cell [#{index},#{col}]: #{my_row[col]}"
      worksheet[index][col].change_contents(my_row[col])
    end
  end

end

app/views/site_urls/_form.html.erb
<%= form_with(model: site_url, local: true) do |form| %>
  <% if site_url.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(site_url.errors.count, "error") %> prohibited this site_url from being saved:</h2>

      <ul>
      <% site_url.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :site %>
    <%= form.text_field :site %>
  </div>

  <div class="field">
    <%= form.label :url %>
    <%= form.text_field :url %>
  </div>

  <div class="field">
    <%= form.label :req_method %>
    <%= form.text_field :req_method %>
  </div>

  <div class="field">
    <%= form.label :code %>
    <%= form.number_field :code %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/site_urls/display.html.erb
<script type="text/javascript">
  $(document).ready(function() {
    $('#jstree_site_urls').jstree({
      'core': {
        'data': <%= raw @tree.to_json %>
      },
      'plugins' : ["themes", "sort", "changed", "types", "wholerow"]
    });
  });
</script>


<h4>  Discovered Urls for Site <%= @site %></h4>
<br />


<div class="row col-md-9 col-lg-9">
  <div id="jstree_site_urls" >
    <ul>
    </ul>
  </div>
</div>

app/views/site_urls/edit.html.erb
<h1>Editing Site Url</h1>

<%= render 'form', site_url: @site_url %>

<%= link_to 'Show', @site_url %> |
<%= link_to 'Back', site_urls_path %>

app/views/site_urls/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Discovered Urls</h1>


<b>Pages: </b><%= will_paginate @site_urls, previous_label: h("<"), next_label: h(">") %>
(25 entries per page)
<span class="text-center">
  &nbsp &nbsp &nbsp &nbsp <b>Total</b>:  <%= @site_urls.count %>
</span> &nbsp &nbsp &nbsp &nbsp
<span class="text-center">
  <%= link_to image_tag("excel.png", size: "35x35", class: "clickable-img", alt: "Download"), site_urls_download_path, method: :post %>
</span>


<table class="table table-bordered table-striped">
  <thead>
    <tr>
      <th>Site</th>
      <th>Url</th>
      <th>Updated</th>
      <th colspan="3">Action</th>
    </tr>
  </thead>

  <tbody>
    <% @site_urls.each do |site_url| %>
      <tr>
        <td><%= link_to site_url.site, site_urls_display_path(:site => site_url.site), target: "_blank" %></td>
        <td><%= site_url.url %></td>
        <td><%= site_url.updated_at %></td>
        <td><%= link_to 'Show', site_url %></td>
        <td><%= link_to 'Edit', edit_site_url_path(site_url) %></td>
        <td><%= link_to 'Destroy', site_url, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Site Url', new_site_url_path %>

app/views/site_urls/new.html.erb
<h1>New Site Url</h1>

<%= render 'form', site_url: @site_url %>

<%= link_to 'Back', site_urls_path %>

app/views/site_urls/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Site:</strong>
  <%= @site_url.site %>
</p>

<p>
  <strong>Url:</strong>
  <%= @site_url.url %>
</p>

<p>
  <strong>Req method:</strong>
  <%= @site_url.req_method %>
</p>

<p>
  <strong>Code:</strong>
  <%= @site_url.code %>
</p>

<%= link_to 'Edit', edit_site_url_path(@site_url) %> |
<%= link_to 'Back', site_urls_path %>