config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}
  devise_scope :user do
    get 'users/list' => 'users#index'
    get 'users/report' => 'users#report'
    get 'users/:id' => 'users#show'
    delete '/users/logout' => 'devise/sessions#destroy'
  end
  get 'users/edit'
  post 'users/edit_save'
  resources :users
  
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  root 'home#page'
  get 'home/page'
  get 'home/support_contact'
  get 'home/about'

  get 'seed/start'
  post 'seed/start'
  get 'seed/load_file'
  post 'seed/save_file'
  get 'seed/discovery'
  post 'seed/discovery'
  get 'seed/distest'
  post 'seed/distest'
  get 'seed/confirm_email'
  post 'seed/confirm_email'

  get 'domains/index'
  get 'domains/show'
  get 'domains/edit'
  post 'domains/edit_domain'
  post 'domains/save_domain'
  post 'domains/edit'
  post 'domains/update'
  delete 'domains/destroy'
  get 'domains/load_file'
  post 'domains/save_file'
  get 'domains/import'
  get 'domains/search'
  get 'domains/search_list'
  post 'domains/search_list'
  post 'domains/save_import'

  get 'cidrs/index'
  get 'cidrs/edit'
  get 'cidrs/import'
  post 'cidrs/save_import'
  post 'cidrs/edit'
  get 'cidrs/load_file'
  post 'cidrs/save_file'

  get 'hosts/index'
  post 'hosts/edit'
  get 'hosts/load_file'
  post 'hosts/save_file'

  get 'support/faq'
  get 'support/contact'

  get 'sites/index'
  get 'sites/show'
  post 'sites/edit'
  get 'sites/load_file'
  post 'sites/save_file'
  post 'sites/search'
  post 'sites/download'

  get 'logs/list'
  get 'logs/show'
  post 'logs/download'

  get 'yml_settings/index'
  get 'yml_settings/load_file'
  post 'yml_settings/save_file'

  get 'reports/index'
  get 'reports/new'
  get 'reports/download'
  get 'reports/download_all'
  resources :reports

  resources :uploads, only: [:new, :create, :destroy]
  get '/uploads/dt'
  get '/uploads/division_1'
  get '/uploads/division_2'
  get '/uploads/division_3'
  post "uploads/update"
  get "uploads/refresh"
  get "uploads/create"
  get "uploads/alert_uploads"

  get 'domain_map/show'
  post 'domain_map/show'

  get 'site_urls/display'
  post 'site_urls/download'
  resources :site_urls

end

app/models/domain.rb
class Domain < ApplicationRecord

  def self.stack_bar_by_keep(div)
=begin
    find_by_sql(<<-MY_SQL
      SELECT
        DATE_FORMAT(start_date, '%Y %M') as 'year_month',
        SUM(CASE WHEN `empt` = 'Full Time' THEN 1 ELSE 0 END) AS `full_time`,
        SUM(CASE WHEN `empt` = 'Temp' THEN 1 ELSE 0 END) AS `temp`,
        SUM(CASE WHEN `empt` = 'Paid Intern' THEN 1 ELSE 0 END) AS `paid_intern`,
        SUM(CASE WHEN `empt` = 'Unpaid Intern' THEN 1 ELSE 0 END) AS `unpaid_intern`,
        SUM(CASE WHEN `empt` = 'Trainee' THEN 1 ELSE 0 END) AS `trainee`,
        SUM(CASE WHEN `empt` = 'Consultant' THEN 1 ELSE 0 END) AS `consultant`

      FROM on_boardings
      GROUP BY DATE_FORMAT(start_date, '%Y %M')
      ORDER BY start_date
      MY_SQL
    ).map do |row|
      [
        row.year_month,
        row.full_time.to_i,
        row.temp.to_i,
        row.paid_intern.to_i,
        row.unpaid_intern.to_i,
        row.trainee.to_i,
        row.consultant.to_i,
        ''
      ]
    end
=end
  end


end

app/controllers/domains_controller.rb
#--
# www_wmap
#
# A  Ruby application for enterprise web application asset tracking
#
# Developed by Sam (Yang) Li, <yang.li@owasp.org>.
#
#++

class DomainsController < ApplicationController
  before_action :authenticate_user!
  include DomainsHelper

    # Custom user import error message
    class ImportLimitError < StandardError
      def message
        "Error exceeding import limit 10 entries."
      end
    end

    # for user search function
    def search_list
      if params[:keyword].nil? or params[:keyword].empty?
        redirect_back :fallback_location => root_path, :alert => "Unrecognized user input. "
      else
        keyword = "%" + params[:keyword].strip + "%"
      end
      @domains = Domain.where('name like ?', keyword).limit(10)
    end

    # search for specific domain info
    def search
      if params[:keyword].nil? or params[:keyword].empty?
        redirect_back :fallback_location => root_path, :alert => "Unrecognized user input. "
      else
        keyword =  params[:keyword].downcase.strip
      end
      @domain = Domain.find_by(name: keyword)
      if @domain.present?
        site_header=["Primary Website","Primary IP","Port","Hosting Status","Server","Response Code","MD5 Fingerprint","Detected Redirection","Timestamp"]
        @prime_site = site_header.zip(site_lookup(@domain.name)).to_h
      else
        @prime_site = nil
      end
    end


    def edit
      #@dir = Pathname.new(Gem.loaded_specs['wmap'].full_gem_path).join('data')
      @dir = Rails.root.join('shared','data')
      @file = @dir.join('domains')
      @uid = current_user.id
    end

    def edit_domain
      @domain=Domain.find_by(name: params[:name])
      @divisions=Domain.distinct.pluck(:division)
      respond_to do |format|
        format.js
      end
    end

    # Allow user to import domain to wmap data file and database table
    def import
      dir = Rails.root.join('shared', 'data')
      Dir.mkdir(dir, 0750) unless Dir.exist?(dir)
      file = dir.join('domains')
      File.new(file, 'w+') unless File.exist?(file)
      f = File.open(file, 'r')
      @restore = ''
      f.each_line { |line| @restore += line }
      f.close
    end

    # Save import from user input
    def save_import
      if platinum_user_and_above?
        uid = current_user.id
        existing_domains = Domain.pluck(:name)
        data_dir = Rails.root.join('shared', 'data')
        # save import to cache file
        file = data_dir.join('domains')
        f = File.open(file, 'w+')
        f.write(params[:file_content])
        f.close
        # calculate the domains from import
        my_domains = Array.new
        params[:file_content].split("\n").map do |x|
          next if x =~ /^\#/
          next if ["",nil].include? x
          my_domains.push(x.split(',')[0])
        end
        raise ImportLimitError if my_domains.size>10
        # remove user defined obsolete domains from db
        domains_to_remove = existing_domains - my_domains
        Domain.where(:name => domains_to_remove).delete_all
        # add user defined new domains into system
        domains_to_add = my_domains - existing_domains
        new_domains = Hash.new
        domains_to_add.map {|y| new_domains[y] = true}
        if new_domains.size > 0
          DomainCheckWorker.perform_async(uid,data_dir.to_s,new_domains)
        end
        render json: { message: 'Saving successed.' }
      else
        render json: { message: 'Access Denied.' }
      end
    rescue ImportLimitError => e
      render json: { message: e.message }
    rescue Psych::SyntaxError
      file = File.open(params[:file_path], 'w+')
      file.write(@restore)
      file.close
      render json: { message: 'Saving failed, please check your file again or contact the site administrator.' }
    end

    def update
      if platinum_user_and_above?
        logger.debug "Current_user attributes: #{current_user.inspect}"
        @domain=Domain.find_by(name: params[:name])
        @domain.division=params[:division][0] unless params[:division].nil?
        @domain.keep=params[:keep] unless params[:keep].nil?
        @domain.current_redirect=params[:current_redirect] unless params[:current_redirect].nil?
        @domain.new_redirect=params[:new_redirect] unless params[:new_redirect].nil?
        @domain.save
        redirect_back :fallback_location => root_path, :alert => "Record is save!"
      else
        redirect_back :fallback_location => root_path, :alert => "Access denied"
      end
    end

    def destroy
      if platinum_user_and_above?
        @domain=Domain.find_by(name: params[:keyword])
        if @domain.destroy
          redirect_to domains_show_all_path, :alert => "Record is deleted!"
        end
      else
        redirect_back :fallback_location => root_path, :alert => "Access denied"
      end
    end

    # show domain info
    def show
      @domain = Domain.find_by("name = ?", params[:name])
    end

    # show all domains
    def index
      @domains = Domain.all.order(sort_column + " " + sort_direction).page(params[:page]).per_page(25)
      @chart_data = pie_by_keep("all").to_json.html_safe
      respond_to do |format|
        format.html #show.html.erb
        format.json { render json: @chart_data }
      end
    end

    # Ajax call from view to local domains records from wmap data file
    def load_file
      data = ''
      #@file = Pathname.new(Gem.loaded_specs['wmap'].full_gem_path).join('data', 'domains')
      @file = Rails.root.join('shared','data','domains')
      file = File.open(@file, 'r')
      file.each_line { |line| data += line }
      file.close
      render plain: data
    end

    # Ajax call from view to save domain records into both wmap data file and database
    def save_file
      if platinum_user_and_above?
        uid = current_user.id
        data_dir = Rails.root.join('shared','data')
        @file = data_dir.join('domains')
        file = File.open(@file, 'r')
        @restore = ''
        file.each_line { |line| @restore += line }
        file.close
        file = File.open(@file, 'w+')
        file.write(params[:file_content])
        file.close
        domain_table_reload(uid,data_dir.to_s)
        render json: { message: 'Saving successful.' }
      else
        render json: { message: 'Saving failed, please check your file again.' }
      end
    rescue Psych::SyntaxError
      file = File.open(@file, 'w+')
      file.write(@restore)
      file.close
      render json: { message: 'Saving failed, please check your file again.' }
    end

    private

    def sort_column
      Domain.column_names.include?(params[:sort]) ? params[:sort] : "name"
    end

    def sort_direction
      %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
    end

end

app/helpers/domains_helper.rb
#--
# www_wmap
#
# A  Ruby application for enterprise web application asset tracking
#
# Developed by Sam (Yang) Li, <yang.li@owasp.org>.
#
#++
require 'erb'

module DomainsHelper
  # make view sortable
  def sortable_domain(column, title = nil, div)
    title ||= column.titleize
    css_class = if column != sort_column
                    nil
                elsif sort_direction == 'asc'
                    'glyphicon glyphicon-chevron-up'
                else
                    'glyphicon glyphicon-chevron-down'
                end
    direction = column == sort_column && sort_direction == 'asc' ? 'desc' : 'asc'
    link_to "#{title} <span class='#{css_class}'></span>".html_safe, division: div, sort: column, direction: direction
  end

  # make view sortable
  def sortable(column, title = nil)
    title ||= column.titleize
    css_class = if column != sort_column
                    nil
                elsif sort_direction == 'asc'
                    'glyphicon glyphicon-chevron-up'
                else
                    'glyphicon glyphicon-chevron-down'
                end
    direction = column == sort_column && sort_direction == 'asc' ? 'desc' : 'asc'
    link_to "#{title} <span class='#{css_class}'></span>".html_safe, sort: column, direction: direction
  end

  # domain to site conversion
  def domain_2_site (domain,port=80)
    puts "Perform simple http(s) service detection on domain #{domain}, port #{port}" if @verbose
    begin
      domain=domain.strip
      if port.to_i == 80
        url_1 = "http://www." + domain + "/"
      elsif port.to_i ==443
        url_1 = "https://www" + domain + "/"
      else
        url_1 = "http://www" + domain + ":" + port.to_s + "/"
        url_2 = "https://www" + domain + ":" + port.to_s + "/"
      end
      puts "Please ensure your internet connection is active before running this method: #{__method__}" if @verbose
      checker=Wmap::UrlChecker.new
      if checker.response_code(url_1) != 10000
        puts "Found URL: #{url_1}" if @verbose
        return url_1
      elsif checker.response_code(url_2) != 10000
        puts "Found URL: #{url_2}" if @verbose
        return url_2
      else
        puts "No http(s) service found on: #{domain}:#{port}" if @verbose
        return nil
      end
    rescue => ee
      puts "Exception on method #{__method__}: #{ee}" if @verbose
      return nil
    end
  end

  # generate pie chart data by 'keep' column
  def pie_by_keep(division)
    chart_data = []
    chart_data.push(["Keep, Redirect or Release?", "Count"])
    if division == "all"
      domains = Domain.select("id,keep, COUNT(*) AS total").group("id, keep")
    else
      domains = Domain.where(division: division).select("id,keep, COUNT(*) AS total").group("id, keep")
    end
    domains.group_by(&:keep).each do |k,v|
       chart_data << [k,v.size]
    end
    return chart_data
  end

  # Lookup the site store for a domain; then return the fingger print info of the site
  def site_lookup(domain)
    tracker=Wmap::SiteTracker.instance
    tracker.verbose=false
    #first order search
    tracker.known_sites.each do |key,val|
      if key.include?(domain.strip.downcase) && key.include?("https")
        tracker=nil
        return [key] + val.values
      end
    end
    #second order search
    tracker.known_sites.each do |key,val|
      if key.include?(domain.strip.downcase)
        tracker=nil
        return [key] + val.values
      end
    end
    tracker=nil
    return [nil]*9
  end

  # look up the wp site data store for a domain; then return the wp finger print info: [is_wp?,wp_ver]
  def wp_site_lookup(domain)
    tracker=Wmap::WpTracker.new(:verbose=>false)
  	# first order
  	tracker.known_wp_sites.each do |key,val|
  		if key.include?(domain.strip.downcase) && val
  			ver=tracker.wp_ver(key)
  			tracker=nil
  			return [val,ver]
  		end
  	end
    # second order
    tracker.known_wp_sites.each do |key,val|
      if key.include?(domain.strip.downcase) && key.include?("https") && val
        tracker=nil
        return [val,nil]
      end
    end
    # third order
    tracker.known_wp_sites.each do |key,val|
      if key.include?(domain.strip.downcase)
        tracker=nil
        return [val,nil]
      end
    end
    tracker=nil
    return [nil,nil]
  end

  # Reload domain table based on the WMAP domains data file
  def domain_table_reload(uid, data_dir)
    puts "Update the domain table ..."
    db = Sequel.connect(ENV['DATABASE_URL'])
    puts "Database connection success. "
    domain_table = db[:domains]
    domain_table.truncate
    puts "Domain table truncate success."
    tracker=Wmap::DomainTracker.instance
    tracker.data_dir = data_dir
    tracker.domains_file = data_dir + "/" + "domains"
    tracker.load_domains_from_file(tracker.domains_file)
    tracker.known_internet_domains.each do |key, val|
      domain_table.insert(name: key,  transferable: val, user_id: uid, created_at: Time.now, updated_at: Time.now)
    end
    tracker=nil
    db = nil
    puts "Update complete. "
  end

  # Import domain from seed file
  def import_domain_from_seed(dir,file)
    puts "Import domain from seed file: #{file}"
    tracker=Wmap::DomainTracker.instance
    tracker.data_dir = dir
    tracker.domains_file = dir + "/" + "domains"
    tracker.load_domains_from_file(tracker.domains_file)
    dis_entries = tracker.file_2_list(file)
    if dis_entries.size > 0
      dis_entries.map do |entry|
        if tracker.is_url?(entry)
          my_host = tracker.url_2_host(entry)
          my_domain = tracker.get_domain_root(my_host)
          tracker.add(my_domain)
        elsif tracker.is_host?(entry)
          my_domain = tracker.get_domain_root(entry)
          tracker.add(my_domain)
        else
          # do nothing
        end
      end
      tracker.save!
    end
    tracker=nil
    puts "Import complete."
  end

end

app/views/domains/_domain.html.erb
<%# Implementation based on this technique: https://github.com/colorfulfool/rails-popup %>
<% remote = request.xhr? %>
<h4>Domain Update</h4>

<br />
<span class="red-star">*
</span>Indicates required field
<%= hidden_field_tag :domain, @domain%>
<%= form_tag(controller: "domains", action: "update", remote: remote, method: "post") do  %>
  <table class="table table-striped" style="border: 1">
      <tr>
        <td>Domain: </td>
        <td><%=@domain.name %></td>
        <td></td> <td></td>

      </tr>
      <tr>
        <td>Divsion: </td>
        <td><%= select(:division, nil, @divisions, {:selected => @domain.division, :include_blank =>false},
              {class: "form-control", required: false}) %>
        </td>

        <td>Keep, Release, Redirect?</td>
        <td ><%= text_field_tag :keep, nil, class: 'form-control', required: false, value: @domain.keep %> </td>
      </tr>
      <tr>
        <td>Current Redirect</td>
        <td ><%= text_field_tag :current_redirect, nil, class: 'form-control', required: false, value: @domain.current_redirect %> </td>

        <td>New Redirect</td>
        <td ><%= text_field_tag :new_redirect, nil, class: 'form-control', required: false, value: @domain.new_redirect %> </td>
      </tr>
      <%= hidden_field_tag :name, params[:name] %>
  </table>
  <p>&nbsp;&nbsp;<button class="btn btn-default btn-sm" type="submit" data-disable-with="Please wait...">Submit</button>
      &nbsp;&nbsp;<input type="button" onclick="window.parent.location = window.parent.location.href;" value="Back" class="btn btn-default btn-sm">
  </p>
<% end %>

app/views/domains/_mini_edit.html.erb
<div class="col-md-2 col-lg-2">
  <button class="btn btn-default dropdown-toggle " data-toggle="dropdown" align="left">
      Edit
      <span class="caret"></span>
  </button>
    <ul class="dropdown-menu">
        <li><%= link_to('Update', domains_edit_domain_path(name: params[:keyword]), :method => :post, :remote => true) %></li>
        <li><%= link_to('Delete', domains_destroy_path(keyword: params[:keyword]), :method => :delete, data: {:confirm => 'Are you sure to remove the record?'} ) %></li>
    </ul>
</div>
<div class="row"> </div>

app/views/domains/edit.html.erb
<script type="text/javascript">
  $(document).ready(function() {
    var domains_editor = CodeMirror(document.getElementById("domainsTextArea"), {
      mode: "null",
      lineNumbers: true,
      extraKeys: {
        "Ctrl-Space": "autocomplete"
      },
      value: ""
    });
    var domains_value =  $.ajax({
      url: "load_file",
      type: "GET",
      dataType: 'text',
      data: {
        "path": ""
      },
      success: function(response) {
        //console.log(response);
        //alert("Success: " + response['message'])
        domains_editor.getDoc().setValue(response);
      },
      error: function(response) {
        //console.log(response);
        alert("Error: " + response['message'])
      }
    });
    $('#save_domains_button').click(function() {
      $.ajax({
        url: "save_file",
        type: "POST",
        dataType: 'json',
        data: {
          "file_path": "",
          "file_content": domains_editor.getDoc().getValue()
        },
        success: function(response) {
          //console.log(response);
          if  (response['message']=="Access Denied.") {
            alert("Access Denied.")
          } else {
            alert("Success: " + response['message'])
          }
        },
        error: function(response) {
          //console.log(response);
          alert("Error:" + response['message'])
        }
      });
      $(location).attr('href', "/cidrs/edit");
    });
  });
</script>

<h4>  Domain Registration </h4>
<br />

<div class="row">

  <div class=" col-md-9 col-lg-9">
    <% data = String.new %>
    <% Dir.mkdir(@dir, 0750) unless Dir.exist?(@dir) %>
    <% File.new(@file, 'w+') unless File.exist?(@file) %>
    <p>
    </br>
    <button class="btn btn-primary" id="save_domains_button" type="submit">Save</button>
    <button type="button" class="pull-right btn btn-default" title="Domain Instructions"
      data-container="body" data-toggle="popover" data-placement="right"
      data-content="Domain Format: <br>
        <ul><li> One entry per line  </li>
            <li> Comment line start with special char # </li>
            <li> Your registered domain name only </li>
            <li> No subdomain such as: www.mydomain.com </li>
            <li> No protocol prefix such as: http://mydomain.com </li>
        </ul>">
      <span class="glyphicon glyphicon-question-sign"></span>Domain Format
    </button>
    <div class ="CodeMirror" id="domainsTextArea">
    </div>

  </div>
</div>

app/views/domains/edit_domain.js.erb
Domain = Popup("<%=j render :partial => 'domains/domain', :format => :html %>", {width: 800}).show('down')

app/views/domains/import.html.erb
<script type="text/javascript">
  $(document).ready(function() {
    var restore=$('#domains').val();
    var domains_editor = CodeMirror(document.getElementById("domainsImportTextArea"), {
      mode: "null",
      lineNumbers: true,
      extraKeys: {
        "Ctrl-Space": "autocomplete"
      },
      value: restore
    });

    $('#save_domains_button').click(function() {
      $.ajax({
        url: "save_import",
        type: "POST",
        dataType: 'json',
        data: {
          "file_content": domains_editor.getDoc().getValue()
        },
        success: function(response) {
          //console.log(response);
          if  (response['message']=="Access Denied.") {
            alert("Access Denied.")
          } else if (response['message']=="Error exceeding import limit of 10 entries.") {
            alert("Error Import Limit - please contact the administrator for help!")
          } else {
            alert("Success: " + response['message']);
            window.location = "/cidrs/import"
          }

        },
        error: function(response) {
          //console.log(response);
          alert("Error:" + response['message'])
        }
      });
    });

    $('#skip_domains_button').click(function() {
      window.location = "/cidrs/import"
    });
  });
</script>

<div class="row">

  <div class=" col-md-9 col-lg-9">
    <p>
    <h4>Please modify / or add your domains below:</h4>
    <button type="button" class="pull-right btn btn-default" title="Import Instructions"
      data-container="body" data-toggle="popover" data-placement="right"
      data-content="Domains Import Format: <br>
      <ul><li> Domain registry example: google.com </li>
          <li> Optional 'free zone transfer detected' field value </li>
          <li> Maximum 10 entries per import </li>
          <li> One entry per line </li>
          <li> Alternatively, click the Skip button if you're not sure </li>
      </ul>
          "><span class="glyphicon glyphicon-question-sign"></span>Domains Format</button>
  </div>
</div>

<input id="domains" type="hidden" value="<%= @restore %>" >

<div class=" col-md-9 col-lg-9">
    <div class ="CodeMirror" id="domainsImportTextArea"></div>
    <p>
    <button class="btn btn-primary" id="save_domains_button" type="submit">Save</button>
    <button class="btn btn-primary" id="skip_domains_button" type="submit">Skip</button>

    </br>
</div>
<div class="row"></div>

app/views/domains/index.html.erb
<script>
  // reload once after Ajax redirect
  $(document).ready(function() {
    if (window.location.href.includes("?")) {
      if (window.location.href.indexOf('reload')==-1) {
           window.location.replace(window.location.href+'&?reload');
      }
    } else {
      if (window.location.href.indexOf('reload')==-1) {
           window.location.replace(window.location.href+'?reload');
      }
    }
  });
</script>

<h4> Domain Portfolio </h4>
<br />

<%= button_to "Edit", domains_edit_path, class: "btn btn-primary" %>

<b>Pages: </b><%= will_paginate @domains, previous_label: h("<"), next_label: h(">") %>
(25 entries per page)
<span class="text-center">
  &nbsp &nbsp &nbsp &nbsp <b>Total</b>:  <%= @domains.count %>
</span> &nbsp &nbsp &nbsp &nbsp
<span class="text-center">
  <%= link_to image_tag("excel.png", size: "35x35", class: "clickable-img", alt: "Download"), reports_download_all_path(:division => "all") %>
</span>
<table class="table table-bordered table-striped">
   <thead>
      <tr>
         <th><%= sortable "name", "Domain" %></th>
         <th>Free Zone Transferable?</th>
         <th>Last Update</th>
      </tr>
   </thead>

   <tbody>
      <% @domains.each do |domain| %>
         <tr>
            <td>
              <% unless domain.name.nil? %>
                  <%= link_to domain.name, domains_search_path(keyword: domain.name), method: "get"  %>
              <% end %>
            </td>
            <td><%if domain.transferable %>
                  <%= "yes" %>
                <% else %>
                  <%= "no" %>
                <% end %>
            </td>
            <td><%= domain.updated_at %></td>

         </tr>
      <% end %>
   </tbody>
</table>

app/views/domains/search.html.erb
<h4>  Domain Information: &nbsp <%= params[:keyword] %></h4>
<br />

<%= render "mini_edit" %>
<br />
<table class="table table-bordered table-striped">
   <tbody>
        <tr> <td>Domain</td> <td><%= @domain.name  %></td> </tr>
        <tr> <td>Division</td> <td><%= @domain.division %></td> </tr>
        <tr> <td>Keep, Release, Redirect?</td> <td><%= @domain.keep %></td> </tr>
        <tr> <td>Current Redirect</td> <td><%= @domain.current_redirect %></td> </tr>
        <tr> <td>New Redirect</td> <td><%= @domain.new_redirect %></td> </tr>
        <tr> <td>Last Update</td> <td><%= @domain.updated_at %></td> </tr>
        <tr> <td>
          <%= button_to "Full View", domain_map_show_path(keyword: params[:keyword]), class: "btn btn-info", form: {target: '_blank'} %> </td>
          <td></td>
        </tr>

      <% if not @prime_site.nil? %>
        <% @prime_site.each do |key,val| %>
          <% if key == "Hosting Status" %>
          <tr> <td><%= key %> &nbsp
              <button type="button" class="btn btn-default" title="Hosting Status"
                data-container="body" data-toggle="popover" data-placement="right"
                data-content="Hosting Status: <br>
                <ul><li> int_hosted - Hosted within one of our data centers </li>
                    <li> ext_hosted - Hosted by one of our ISP  </li>
                </ul>
                    "> <span class="glyphicon glyphicon-question-sign"></span></button>
            </td>
            <td>  <%= val %>  </td>
          </tr>
          <% elsif key == "Response Code" %>
          <tr> <td><%= key %> &nbsp
              <button type="button" class="btn btn-default" title="Response Code"
                data-container="body" data-toggle="popover" data-placement="right"
                data-content="Default web page HTTP response status code. Refer to <a href='https://en.wikipedia.org/wiki/List_of_HTTP_status_codes'>this article</a> for the complete list.
                  "> <span class="glyphicon glyphicon-question-sign"></span></button>
            </td>
            <td>  <%= val %>  </td>
          </tr>
          <% elsif key == "MD5 Fingerprint" %>
          <tr> <td><%= key %> &nbsp
              <button type="button" class="btn btn-default" title="MD5 Fingerprint"
                data-container="body" data-toggle="popover" data-placement="right"
                data-content="Default web page HTTP payload MD5 hash value. It may be used to identify unique website.
                  "> <span class="glyphicon glyphicon-question-sign"></span></button>
            </td>
            <td>  <%= val %>  </td>
          </tr>          <% else %>
            <tr> <td><%= key %></td> <td> <%=val %> </td> </tr>
          <% end %>
        <% end %>
      <% end %>
   </tbody>
</table>

app/views/domains/search_list.html.erb
<h4> Domain Search:  &nbsp <%= params[:keyword] %></h4>
<div class="row"></div>

<h5>Search Results: </h5>
<div class="list-group">
    <ul>
    <% index=0; for domain in @domains; next if domain.nil?; index+=1 %>
        <%= index %>. &nbsp<u><%= link_to domain.name, domains_show_path(name: domain.name), method: "get", target: "_blank" %></u>
        <br />
    <% end %>
    </ul>

  <table>
    <% if @domains.size == 0 %>
    <tr><td> Can't find your interest here? Consider using a less restrict search string. Or contact the <a href='mailto:yang.li@owasp.org'>maintainer</a> directly. </td></tr>
    <% elsif @domains.size >= 10 %>
    <tr><td>Maximum <b>10</b> records retrieval quota exceed. Can't find your interest here? Consider using a more restrict search string.</td></tr>
    <% end %>
  </table>

</div>